### ISSUE TITLE
Device object

### ISSUE THREAD

**Issue by VeriHeppi** [MobileMESH/ProjectM#29]
Create an object that stores the device information.

- MAC address
- Device Name
- Location data
- All nodes in the network
- All Available Nodes
- Notifications (true/false)
- Saving data on the device locally

**Comment by VeriHeppi** [comment]
Created a new branch "29-DeviceObj" and added the class Device and some essential variables required for the MeshManager class. When you start work on this just be sure to pull that branch and work on that Device class.

**Comment by vnuotio** [comment]
Device.kt class should be moved from _fi.mobilemesh.projectm.network_ to fi.mobilemesh.projectm.objects (on branch 32-message-history) at some point to streamline project structure

**Comment by vnuotio** [comment]
Function for refreshing (clearing and adding nearby devices)
