### ISSUE TITLE
Saving user's preferences

### ISSUE THREAD

**Issue by DiyazY** [MobileMESH/ProjectM#60]
Saving and loading user settings locally using SharedPreferences
https://developer.android.com/training/data-storage/shared-preferences

**Comment by vnuotio** [comment]
Also functions for
* Saving user's unique ID (UUID)
* Getting said ID

**Comment by VeriHeppi** [comment]
- Share location to other devices (true/false)
-        Location sharing means if the user is seen on a map to other users. This does not mean disabling the GPS sensor on the device.
