### ISSUE TITLE
1:1 connection between 2 devices

### ISSUE THREAD

**Issue by VeriHeppi** [MobileMESH/ProjectM#7]
Using WiFi-Direct connect 2 devices and share some data between them

**Comment by vnuotio** [comment]
* Basic tutorial used: https://stuff.mit.edu/afs/sipb/project/android/docs/guide/topics/connectivity/wifip2p.html
* Good docs: https://stuff.mit.edu/afs/sipb/project/android/docs/reference/android/net/wifi/p2p/WifiP2pManager.html

**Comment by VeriHeppi** [comment]
1 to 1 connection working now and merged in to main branch.
